# Generated by Django 5.1.3 on 2024-12-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservationroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
