# Generated by Django 5.1.3 on 2024-12-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
